name: Build
on:
  push:
    branches:
    - feature/*
    - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  maven-ci:

    uses: savitri443/maven-reusable-workflow/.github/workflows/maven-reusable-workflow.yml@main
    with:
      java-version: '17' # or '21', '11', etc. as needed
