name: Maven CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact.jar
          path: target/*.jar

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
          

      - name: Notify build status
        run: echo "Build completed successfully!"
        # You can replace this with a notification action or script if needed.
        # For example, you could use Slack, email, or any other notification service.