name: Maven CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:

    uses: savitri443/maven-reusable-workflow/blob/main/maven-reusuable-workflow.yml@main
    with:
      java-version: '17' # or '21', '11', etc. as needed
